development:
  adapter: postgresql
  database: overflowing_development
  host: localhost
  encoding: UTF8
  min_messages: WARNING

test: &test
  adapter: postgresql
  database: overflowing_test
  host: localhost
  encoding: UTF8
  min_messages: WARNING

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
